# Generated by Django 3.2.18 on 2023-05-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
